version: '3'
services:
  api:
    container_name: my_users_api
    build:
      context: .
      target: production
    entrypoint: python3 run.py
    env_file:
      - .env
    depends_on:
      - db
      - cache
    ports:
      - '5000:5000'
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=kopudoju
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
    environment:
      FLASK_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: kopudoju
      DB_NAME: polls
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: kopudoju
    links:
      - db
      - cache
volumes:
  db:
    driver: local
  cache:
    driver: local